### PR TITLE
Local docker-compose improvements

### PR DESCRIPTION
**Pull request by joe-elliott**
- Fixed dashboard expressions
- Fixed exemplar links in the dashboard

I also tried to get the dashboard links to Tempo search to use TraceQL but couldn't get it to work properly.

### CODE REVIEW

**Comment by joe-elliott** [comment]
ok, just rebased. apparently all i did was fix exemplar linking :)

**Comment by joe-elliott** [comment]
More changes!

The changes here are necessary for me to get anything to show in the dashboard. I don't know if I have a weird version or something, but w/o these changes the mlt dashboard is blank.

Also, I can't get the service version drop down to work. None of the mythical components produce a metric with ` `service_version` label.

**Comment by hedss** [comment]
I think something superweird is going on then. A clean clone for me and startup has the dashboard working and I get results for all the dropdowns.... hmm.

Exemplars work to (seeing the change made to `traceID`). Not sure what's going on for you.

**Comment by hedss** [comment]
Closed due to more recent changes (see #34).

General plan is to tend this repository a lot more as it's now included in the documentation of at least of our TSDBs.

**Pull request closed without merging**
